name: Create Custom image using Packer

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Testing and building jar
    runs-on: ubuntu-latest
    env:
        DB_DATABASE: ${{secrets.DATABASE_NAME}}
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Initialize MYSQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -h localhost -e "CREATE DATABASE IF NOT EXISTS MYSQL_DATABASE;" -u$MYSQL_DATABASE_USERNAME -p$MYSQL_DATABASE_PASSWORD
      # - name: Build with Maven
      #   run: mvn -B package -DskipTests --file pom.xml

  packer:
    name: Building custom image with Packer
    runs-on: ubuntu-latest
    needs: build
    env:
      SERVICE_ACCOUNT_JSON: ${{secrets.CREDENTIALS_JSON}}
      project_id: ${{secrets.PROJECT_ID}}
      SERVICE_ACCOUNT_EMAIL: ${{secrets.SERVICE_ACCOUNT_EMAIL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup-packer

      - name: Init Packer
        run: packer init packer/custom-image.pkr.hcl

      - name: Build image
        run: packer build -var 'credentials_json={{env "SERVICE_ACCOUNT_JSON"}}' -var 'project_id={{env "PROJECT_ID"}}' -var 'service_account_email={{env "GCP_SERVICE_ACCOUNT_EMAIL"}}'  ./packer/custom-image.pkr.hcl
        env: 
          name: Building custom image with Packer
          runs-on: ubuntu-latest
          needs: build