name: Packer Build Workflow

on:
  pull_request:
    branches: [ "main" ]
    # types:
        # - closed

jobs:
  jobs1:
    # if: github.event.pull_request.merged == true
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PKR_VAR_project_id: ${{secrets.PROJECT_ID}}
      PKR_VAR_source_image_family: ${{secrets.SOURCE_IMAGE_FAMILY}}
      PKR_VAR_custom_image_zone: ${{secrets.CUSTOM_IMAGE_ZONE}}
      PKR_VAR_ssh_username: ${{secrets.SSH_USERNAME}}
      PKR_VAR_custom_image_network: ${{secrets.CUSTOM_IMAGE_NETWORK}}
      PKR_VAR_custom_image_name: ${{secrets.CUSTOM_IMAGE_NAME}}
      PKR_VAR_custom_image_description: ${{secrets.CUSTOM_IMAGE_DESCRIPTION}}
      PKR_VAR_service_account_email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Log Directory
        run: |
          sudo chmod -R 733 /var/log
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Google Cloud Platform Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.CREDENTIALS_JSON}}'

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Packer Init
        working-directory: ./packer
        run: "packer init ."

      - name: Packer Build
        working-directory: ./packer
        run: "packer build ."

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
               DATABASE_URL:projects/217948701680/secrets/DATABASE_URL/versions/1
               DATABASE_PASSWORD:projects/217948701680/secrets/DATABASE_PASSWORD/versions/1
               DATABASE_USERNAME:projects/217948701680/secrets/DATABASE_USERNAME/versions/1

      - name: Create Instance Template
        run: |
          gcloud compute instance-templates create instance-template-1 \
            --machine-type n2-standard-2 \
            --instance-template-region=us-east1 \
            --create-disk=image=projects/csye6225-dev-123/global/images/centos-custom-image-google-1712749482,size=100,type=pd-balanced,auto-delete=yes \
            --network=projects/csye6225-dev-123/global/networks/vpc-network \
            --subnet=projects/csye6225-dev-123/regions/us-east1/subnetworks/webapp \
            --metadata startup-script="echo 'DATABASE_URL=${{steps.secrets.outputs.DATABASE_URL}}' > .env && echo 'DATABASE_USERNAME=${{steps.secrets.outputs.DATABASE_USERNAME}}' >> .env && echo 'DATABASE_PASSWORD=${{steps.secrets.outputs.DATABASE_PASSWORD}}' >> .env && sudo mv .env /opt/ && sudo chown csye6225:csye6225 /opt/.env && sudo setenforce 0 && sudo systemctl daemon-reload && sudo systemctl restart start-webapp.service" \
            --service-account csye6225-packer@csye6225-dev-123.iam.gserviceaccount.com \
            --tags=vm-instance

      - name: Set Instance Template
        run: | 
          gcloud compute instance-groups managed set-instance-template \
            projects/csye6225-dev-123/regions/us-east1/instanceGroupManagers/webappserver-igm \
            --template=projects/csye6225-dev-123/regions/us-east1/instanceTemplates/instance-template-1
      
      - name: Apply instance template to the managed instance group
        run: |
          gcloud compute instance-groups managed rolling-action start-update projects/csye6225-dev-123/regions/us-east1/instanceGroupManagers/webappserver-igm \
            --version=template=projects/csye6225-dev-123/regions/us-east1/instanceTemplates/instance-template-1
    
      - name: Verify version target reached
        run: |
          gcloud compute instance-groups managed wait-until projects/csye6225-dev-123/regions/us-east1/instanceGroupManagers/webappserver-igm --version-target-reached \
    
      - name: Describe instance group
        run: |
          gcloud compute instance-groups managed describe projects/csye6225-dev-123/regions/us-east1/instanceGroupManagers/webappserver-igm --format=json | jq '.versionTargetReached' \