name: Packer Build Workflow

on:
  pull_request:
    branches: [ "main" ]
    types:
        - closed

jobs:
  jobs1:
    if: github.event.pull_request.merged == true
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PKR_VAR_project_id: ${{secrets.PROJECT_ID}}
      PKR_VAR_source_image_family: ${{secrets.SOURCE_IMAGE_FAMILY}}
      PKR_VAR_custom_image_zone: ${{secrets.CUSTOM_IMAGE_ZONE}}
      PKR_VAR_ssh_username: ${{secrets.SSH_USERNAME}}
      PKR_VAR_custom_image_network: ${{secrets.CUSTOM_IMAGE_NETWORK}}
      PKR_VAR_custom_image_name: ${{secrets.CUSTOM_IMAGE_NAME}}
      PKR_VAR_custom_image_description: ${{secrets.CUSTOM_IMAGE_DESCRIPTION}}
      PKR_VAR_service_account_email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Creating .env file
        run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" > .env
          echo "DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}" >> .env
          echo "DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}" >> .env
      - name: Google Cloud Platform Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.CREDENTIALS_JSON}}'

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Packer Init
        working-directory: ./packer
        run: "packer init ."

      - name: Packer Fmt
        working-directory: ./packer
        run: packer fmt .

      - name: Packer Validate
        working-directory: ./packer
        run: "packer validate ."

      - name: Packer Build
        working-directory: ./packer
        run: "packer build ."